### PR TITLE
Feature/external config

### PR DESCRIPTION
**Pull request by ghost**
- I implemented a YAML based external config with pykwalify schema and validation.
- I also organized the project into a package instead of a single module.
- I added a gitignore for a Emacs, Pycharm and Python to keep junk from getting into the repository.

### CODE REVIEW

**Comment by jmb** [comment]
Looking great - I've got it running with a few tweaks and corrections on my hardware.

I just need to work out how to push my changes back onto this branch!

**Comment by jmb** [comment]
Hopefully that's made my changes ok - can you take another look?

**Comment by ghost** [comment]
Looks good to me. Nice catch with the chip name thing.

**Comment by ghost** [comment]
Are you able to merge this? I'd like to receive credit for Hacktoberfest :)

**Comment by jmb** [comment]
Merged - you do actually get credit for open PRs too - no need for them to be merged!

**Comment by ghost** [comment]
Ah, I understand. Thanks!

Em 15 de out de 2017 03:15, "Jonathan Batchelor" <notifications@github.com>
escreveu:

**Pull request merged**
